### ISSUE TITLE
支付宝版本10.6.66.8000无法正常使用

### ISSUE THREAD

**Issue by ClayTT** [lazy-immortal/Sesame#5]
### 程序版本 / 框架版本 / 模块版本

支付宝版本10.6.66.8000
LSPosed-JingMatrix 1.10.1（7136）
模块版本芝麻粒1.6.0

### 系统版本 / Android版本

hyperOS 2.0.3.2   A15

### 详细描述问题发生的具体原因

支付宝是重新安装的，模块也是重新安装的，LSP正常设置，打开支付宝后，模块未正常工作。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

00:50:29.338 ERROR: LibraryUtil, android.content.pm.PackageManager$NameNotFoundException: io.github.lazyimmortal.sesame
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:532)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:515)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:509)
	at io.github.lazyimmortal.sesame.util.LibraryUtil.getLibSesamePath(LibraryUtil.java:16)
	at io.github.lazyimmortal.sesame.hook.ApplicationHook$3.afterHookedMethod(ApplicationHook.java:194)
	at SmeXd.DQaSSkoEpJz.n.cW.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(Unknown Source:279)
	at LSPHooker_.onCreate(Unknown Source:8)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5392)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2693)
	at com.alipay.stability.workaround.a.a.__handleMessage_stub_private(SourceFile:33)
	at com.alipay.stability.workaround.a.a.__handleMessage_stub(Unknown Source:29)
	at com.alipay.dexaop.perf.CallbackHandleMessageChain.proceed1(SourceFile:15)
	at com.alipay.dexaop.monitor.chain.interceptors.RunningObjectInterceptor.intercept1(Unknown Source:89)
	at com.alipay.dexaop.perf.CallbackHandleMessageChain.proceed1(SourceFile:30)
	at com.alipay.dexaop.DexAOPEntrySettings.android_os_Handler_Callback_handleMessage_proxy(SourceFile:13)
	at com.alipay.dexaop.DexAOPEntry.android_os_Handler_Callback_handleMessage_proxy(Unknown Source:0)
	at com.alipay.stability.workaround.a.a.handleMessage(Unknown Source:44)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:249)
	at android.os.Looper.loop(Looper.java:337)
	at android.app.ActivityThread.main(ActivityThread.java:9591)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:615)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

</code></pre></details>

**Comment by lazy-immortal** [comment]
~~隐藏应用列表~~

**Comment by xiaowei456** [comment]
怎么光盘没有了

**Comment by lazy-immortal** [comment]
> 怎么光盘没有了

你仔细再看看？

**Comment by jisholen** [comment]
虚拟机里面打开就闪退，
vmos安卓7.1
怎么回事大佬？

**Comment by Roymod** [comment]
同样的问题，1.52老版本没弹，新版本1.60开始就是芝麻关门，删除模块和支重新安装还是不行，没有隐藏列表模块
